version: "3.3"

services:
  mysql:
    restart: unless-stopped
    image: mysql:8.0.27
    env_file:
      - .env
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=db_price
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  warehouse:
    image: aresprotocollab/warehouse:latest
    container_name: warehouse
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "5566:5566"
    volumes:
      - ./configs:/opt/configs:ro
      - ./logs:/opt/logs
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command:
      sh -c "./warehouse"

