interval = 60
port = 5566
insertInterval = 5 #insert db interval  time = insertInterval * interval
maxMemTime = 18000  #max memory time in memory （second）
pageSize = 20 
retryCount = 3
user = "root"
password = "49ba59abbe56e057"
proxy = "http://127.0.0.1:7890/"

symbols = ["btc-usdt", "eth-usdt", "link-usdt", "snx-usdt", "1inch-usdt", "dot-usdt", "aave-usdt",
"bch-usdt", "bnb-usdt", "comp-usdt", "dash-usdt", "eos-usdt", "etc-usdt", "fil-usdt", "ht-usdt",
"knc-usdt", "ltc-usdt", "uni-usdt", "xrp-usdt", "xtz-usdt", "ada-usdt", "bnt-usdt", "doge-usdt",
"matic-usdt", "mkr-usdt", "omg-usdt", "ont-usdt", "sushi-usdt", "trx-usdt", "xmr-usdt", "yfi-usdt",
"zec-usdt", "bat-usdt", "crv-usdt", "ksm-usdt", "lrc-usdt", "near-usdt", "okb-usdt", "zrx-usdt",
"sol-usdt", "atom-usdt", "xlm-usdt", "icp-usdt", "algo-usdt", "neo-usdt", "ftm-usdt", "dcr-usdt",
"mana-usdt", "iost-usdt", "qtum-usdt", "zil-usdt"]

[mysql]
server = "127.0.0.1"
port = 3306
db = "db_price"
name = "root"
password = "Xjz!1234"

[exchange.1]
name = "binance"
weight = 1
url = "https://api.binance.com/api/v3/ticker/price?symbol={$symbol}"

[exchange.2]
name = "huobi"
weight = 1
url = "https://api.huobi.pro/market/detail/merged?symbol={$symbol}"

[exchange.3]
name = "bitfinex"
weight = 1
url = "https://api-pub.bitfinex.com/v2/tickers?symbols=t{$symbol}"

[exchange.4]
name = "ok"
weight = 1
url = "https://www.okex.com/api/spot/v3/instruments/{$symbol1}-{$symbol2}/ticker"

[exchange.5]
name = "coinbase"
weight = 1
url = "https://api.pro.coinbase.com/products/{$symbol}/book"

[exchange.6]
name = "bitstamp"
weight = 1
url = "https://www.bitstamp.net/api/v2/ticker/{$symbol}"



