interval = 60
port = 5566
insertInterval = 5 #insert db interval  time = insertInterval * interval
maxMemTime = 18000  #max memory time in memory （second）
pageSize = 20 
retryCount = 3
user = "root"
password = "49ba59abbe56e057"
# proxy = "http://127.0.0.1:7890/"
proxy = ""

# 77
symbols = [
    "btc-usdt", "eth-usdt", "ada-usdt", "xrp-usdt", "sol-usdt", "dot-usdt", "doge-usdt",
    "avax-usdt", "luna-usdt", "uni-usdt", "ltc-usdt", "bch-usdt", "link-usdt", "ftt-usdt",
    "atom-usdt", "fil-usdt", "matic-usdt", "trx-usdt", "xlm-usdt", "vet-usdt", "icp-usdt",
    "etc-usdt", "theta-usdt", "algo-usdt", "xmr-usdt", "xtz-usdt", "eos-usdt", "egld-usdt",
    "axs-usdt", "aave-usdt", "iota-usdt", "ftm-usdt", "ksm-usdt", "hbar-usdt", "neo-usdt",
    "waves-usdt", "mkr-usdt", "near-usdt", "btt-usdt", "dash-usdt", "snx-usdt", "chz-usdt",
    "comp-usdt", "stx-usdt", "dcr-usdt", "xem-usdt", "omg-usdt", "zec-usdt", "sushi-usdt",
    "enj-usdt", "mana-usdt", "yfi-usdt", "iost-usdt", "qtum-usdt", "bat-usdt", "zil-usdt",
    "icx-usdt", "grt-usdt", "celo-usdt", "zen-usdt", "ren-usdt", "sc-usdt", "zrx-usdt",
    "ont-usdt", "nano-usdt", "crv-usdt", "bnt-usdt", "fet-usdt", "uma-usdt", "iotx-usdt",
    "lrc-usdt", "sand-usdt", "srm-usdt", "1inch-usdt", "kava-usdt", "knc-usdt", "bnb-usdt"]


[mysql]
server = "127.0.0.1"
port = 3306
db = "db_price"
name = "root"
# password = "Xjz!1234"
password = "zywl"

[exchange.1]
name = "binance"
weight = 1
url = "https://api.binance.com/api/v3/ticker/price?symbol={$symbol}"

[exchange.2]
name = "huobi"
weight = 1
url = "https://api.huobi.pro/market/detail/merged?symbol={$symbol}"

[exchange.3]
name = "bitfinex"
weight = 1
url = "https://api-pub.bitfinex.com/v2/tickers?symbols=t{$symbol}"

[exchange.4]
name = "ok"
weight = 1
url = "https://www.okex.com/api/spot/v3/instruments/{$symbol1}-{$symbol2}/ticker"

[exchange.5]
name = "coinbase"
weight = 1
url = "https://api.pro.coinbase.com/products/{$symbol}/book"

[exchange.6]
name = "bitstamp"
weight = 1
url = "https://www.bitstamp.net/api/v2/ticker/{$symbol}"



