interval = 60
port = 5566
proxy = "http://127.0.0.1:7890/"

symbols = ["btcusdt", "ethusdt", "dotusdt"]

[mysql]
server = "127.0.0.1"
port = 3306
db = "db_price"
name = "root"
password = "Xjz!1234"

[exchange.1]
name = "binance"
weight = 1
url = "https://api.binance.com/api/v3/ticker/price?symbol={$symbol}"

[exchange.2]
name = "huobi"
weight = 1
url = "https://api.huobi.pro/market/detail/merged?symbol={$symbol}"

